/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TendancesRouteImport } from './routes/tendances'
import { Route as VeillesRouteImport } from './routes/veilles'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TendancesRoute = TendancesRouteImport.update({
  id: '/tendances',
  path: '/tendances',
  getParentRoute: () => rootRouteImport,
} as any)
const VeillesRoute = VeillesRouteImport.update({
  id: '/veilles',
  path: '/veilles',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/sources': typeof SourcesRoute
  '/tendances': typeof TendancesRoute
  '/veilles': typeof VeillesRoute
  '/articles/$id': typeof ArticlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/sources': typeof SourcesRoute
  '/tendances': typeof TendancesRoute
  '/veilles': typeof VeillesRoute
  '/articles/$id': typeof ArticlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/sources': typeof SourcesRoute
  '/tendances': typeof TendancesRoute
  '/veilles': typeof VeillesRoute
  '/articles/$id': typeof ArticlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/parametres'
    | '/rapports'
    | '/sources'
    | '/tendances'
    | '/veilles'
    | '/articles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/parametres'
    | '/rapports'
    | '/sources'
    | '/tendances'
    | '/veilles'
    | '/articles/$id'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/parametres'
    | '/rapports'
    | '/sources'
    | '/tendances'
    | '/veilles'
    | '/articles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  ParametresRoute: typeof ParametresRoute
  RapportsRoute: typeof RapportsRoute
  SourcesRoute: typeof SourcesRoute
  TendancesRoute: typeof TendancesRoute
  VeillesRoute: typeof VeillesRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendances': {
      id: '/tendances'
      path: '/tendances'
      fullPath: '/tendances'
      preLoaderRoute: typeof TendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veilles': {
      id: '/veilles'
      path: '/veilles'
      fullPath: '/veilles'
      preLoaderRoute: typeof VeillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  ParametresRoute: ParametresRoute,
  RapportsRoute: RapportsRoute,
  SourcesRoute: SourcesRoute,
  TendancesRoute: TendancesRoute,
  VeillesRoute: VeillesRoute,
  ArticlesIdRoute: ArticlesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
